### ISSUE TITLE
Notebook listing on homepage

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#13]
Can we put the title of blog posts over the image and not show the author info or date on the homepage? Basically, can we make them look like the story blocks? I think it will look cleaner.

**Comment by stvnspchr** [comment]
Here's that change 0322429ba48738245d0da4098cd0d0c611c1a11d. It's sort of goofy. I may revisit at some point. I'd like to use the Read More box too. But the thumbs are a little too small. Closed for now.
