### ISSUE TITLE
Notebook hero image

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#14]
I like the format of the Notebook page. But can we make the title image look more similar to a Catagory page? With "PBT NOTEBOOK" in big type, then a semi-colon and the description in smaller font.

The roll-over change to "read more" looks great!

**Comment by stvnspchr** [comment]
8029acfdc131164f2f1abe4a3033b583b784132c

Used featured post meta to display the title. Also make the hero image shorter.
