### ISSUE TITLE
Explore page sub-basins

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#15]
When I view the explore page, the bottom list of sub-basins does not show up--only the very top of each button shows. Can't seem to make it show even with a larger screensize.

**Comment by stvnspchr** [comment]
This is just because you are logged in and the wp-admin bar pushed the full-width page down 32px. It will only be an issue for site admins when logged in. I fixed that style here 0827715ac98ad1a095321009063512e51174243c though
