### ISSUE TITLE
About Page change

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#16]
On each user's page, instead of "Steven's Credits" can we change credits to "Work" or "Posts"? Thanks.

**Comment by abrocious** [comment]
I think work makes the most sense. That encompasses videos and other associated media.

**Comment by stvnspchr** [comment]
dfbcc4a
dfbcc4ae3341f7392bfa0fb9629909f7bd1eaee6
Changed here. Unfortunately, the author page only includes the posts that author actually posted, not ones that they are listed in the secondary author section. I will change that in another commit.
