### ISSUE TITLE
Emails on About page

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#18]
Can we hide emails on the About page for contributors who don't have professional (NET) email addresses they want shown?

**Comment by stvnspchr** [comment]
What if these users were displayed in a different section, like 'Contributors'. Could we then display their emails? Or do we just want an option for 'public email'? A default user has to have an email.

**Comment by stvnspchr** [comment]
This could be solved with #8 too

**Comment by stvnspchr** [comment]
c8719d8c8142edf4d9875df9d2b85dd5e212e054 Fixed here.
