### ISSUE TITLE
Font size for homepage blog post list

### ISSUE THREAD

**Issue by abrocious** [plattebasintimelapse/pbt-wp-theme#21]
Can we increase the font size for the titles of blog posts on the homepage, so that it matches the stories? I think it looks a little slim.

**Comment by stvnspchr** [comment]
I think 64d130da1f081139dfa021437b8b6c6ea6a9e4c6 should handle this. I made the thumbnails smaller for smaller screen sizes. The font should take up more of the space, not so thin.
