### ISSUE TITLE
Handle Image Styling Without Captions

### ISSUE THREAD

**Issue by mlundgren** [plattebasintimelapse/pbt-wp-theme#3]
Images without captions will not allow featured image styling.

**Comment by stvnspchr** [comment]
I'll have to think about how when the caption short code runs and if images do not get formatted with the HTML5 figure tag. The DOM structure is dissimilar to the short coded DOM, thus styling is lacking.

**Comment by stvnspchr** [comment]
Okay, had to style the imgs with a child selector. Then undo that margin for the short code generated margins. ffa12f65c2a115d0291d7006624f7b0e209ae729
